app "980255991"

primary_category "Entertainment"
secondary_category "Reference"

price_tier 0

screenshots_path "./fastlane/screenshots"
app_icon "./fastlane/AppIcon.png"
app_rating_config_path "./fastlane/ratings.json"
copyright "Ayan Yenbekbay"

app_review_information(
  first_name: "Ayan",
  last_name: "Yenbekbay",
  phone_number: "6126444413",
  email_address: "ayan.yenb@gmail.com"
)
automatic_release true

name({
  'ru' => "Сеансы - афиша кинотеатров Казахстана"
})

description({
  'ru' => "Сеансы - самый удобный способ организовать поход в кино.

- Простой выбор сеанса в кинотеатре вашего города
- Полная информация о фильмах – рейтинги, трейлеры, актерский состав, рецензии и многое другое
- Фильтрация и сортировка фильмов по различным критериям
- Сортировка и обзор кинотеатров вашего города на карте
- Хранение избранных кинотеатров
- Новости индустрии кино из различных источников
- Поиск фильмов через функцию Spotlight
- Виджет в центре уведомлений для быстрого доступа к самым популярным фильмам

Если вам нравится Сеансы, пожалуйста, уделите нам минуту и поставьте приложению хороший рейтинг. И если у вас есть какое-либо предложение или отзыв, напишите мне на ayan.yenb@gmail.com."
})

keywords(
  'ru' => "кино,кинотеатры,кинотеатр,kino.kz,kino,kiwi,кинозавр,кинопоиск,афиша,фильмы,Алматы,Астана"
)
